services:
  - type: web
    name: vpat-report
    runtime: python
    buildCommand: "apt-get install -y wkhtmltopdf && pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
envVars:
  - key: XDG_RUNTIME_DIR
    value: /tmp/runtime-render
